# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            'musings of a starseed'
tagline:          'eye have always been naked'
description:      'already naked'
url:              http://musingsofastarseed.tk
baseurl:          /

author:
  name:           'STARSEED'
  url:            

jekyll-archives:
  enabled: []
  layout: 'archive'
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
    category: '/category/:name/'

paginate:         6

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
