# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            'be light'
tagline:          'om'
description:      'light musings'
url:              http://musingsofastarseed.tk
baseurl:          /

author:
  name:           ''
  url:            

pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/atom.xml'

paginate:         6

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
