# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            'the aesthetic'
tagline:          'Streetwear Reviews'
description:      'Perspectives on streetwear aesthetics and symbolism'
url:              http://musingsofastarseed.tk
baseurl:          /

author:
  name:           ''
  url:            


paginate:         6

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
